"""Add drive fields to course and enrollment

Revision ID: 06f4a841bf85
Revises: 637ce8b79f16
Create Date: 2026-07-23 23:12:13.958579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f4a841bf85'
down_revision: Union[str, None] = '637ce8b79f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'selected_seva',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_appointments_razorpay_order_id'), 'appointments', ['razorpay_order_id'], unique=False)
    op.add_column('courses', sa.Column('drive_folder_id', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('access_duration_days', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrollments', sa.Column('drive_permission_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'drive_permission_id')
    op.drop_column('enrollments', 'expiry_date')
    op.drop_column('courses', 'access_duration_days')
    op.drop_column('courses', 'drive_folder_id')
    op.drop_index(op.f('ix_appointments_razorpay_order_id'), table_name='appointments')
    op.alter_column('appointments', 'selected_seva',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
