"""add_unique_constraint_to_enrollments

Revision ID: 11ad60743dde
Revises: 830d7aec0434
Create Date: 2026-07-17 19:21:51.473268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ad60743dde'
down_revision: Union[str, None] = '830d7aec0434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollment_user_course', 'enrollments', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollment_user_course', 'enrollments', type_='unique')
    # ### end Alembic commands ###
