"""Add astrology fields to users

Revision ID: 637ce8b79f16
Revises: ca3a0428ee52
Create Date: 2026-07-18 13:17:55.653085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637ce8b79f16'
down_revision: Union[str, None] = 'ca3a0428ee52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_files_id'), 'consultation_files', ['id'], unique=False)
    op.create_table('lecture_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lecture_id', name='uq_lecture_progress_user_lecture')
    )
    op.create_index(op.f('ix_lecture_progress_id'), 'lecture_progress', ['id'], unique=False)
    op.add_column('appointments', sa.Column('report_file_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('birth_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_lon')
    op.drop_column('users', 'birth_lat')
    op.drop_column('appointments', 'report_file_url')
    op.drop_index(op.f('ix_lecture_progress_id'), table_name='lecture_progress')
    op.drop_table('lecture_progress')
    op.drop_index(op.f('ix_consultation_files_id'), table_name='consultation_files')
    op.drop_table('consultation_files')
    # ### end Alembic commands ###
