"""Change agora_channel to google_meet_link

Revision ID: 6574a724e8fd
Revises: 96b60131d848
Create Date: 2026-07-17 21:40:13.721374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6574a724e8fd'
down_revision: Union[str, None] = '96b60131d848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('google_meet_link', sa.String(), nullable=True))
    op.drop_column('appointments', 'agora_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('agora_channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'google_meet_link')
    # ### end Alembic commands ###
