"""Add is_active to enrollment

Revision ID: 96b60131d848
Revises: 11ad60743dde
Create Date: 2026-07-17 21:34:25.410365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b60131d848'
down_revision: Union[str, None] = '11ad60743dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'is_active')
    # ### end Alembic commands ###
